agent: sem_exp
alpha: 0.99
auto_gpu_config: 1
camera_height: 0.88
cat_pred_threshold: 5.0
clip_param: 0.2
collision_threshold: 0.1
du_scale: 1
dump_location: ./tmp/
entropy_coef: 0.001
env_frame_height: 480
env_frame_width: 640
eps: 1.0e-05
eval: 0
exp_name: exp1
exp_pred_threshold: 1.0
floor_thr: 50.0
frame_height: 120
frame_width: 160
gamma: 0.99
global_downscaling: 2
global_hidden_size: 256
hfov: 79.0
intrinsic_rew_coeff: 0.05
load: '0'
load_se_edge: '0'
log_interval: 10
lr: 2.5e-05
map_pred_threshold: 1.0
map_resolution: 5
map_size_cm: 4800
max_d: 100.0
max_depth: 5.0
max_episode_length: 500
max_grad_norm: 0.5
min_d: 1.5
min_depth: 0.5
no_cuda: false
num_eval_episodes: 400
num_global_steps: 20
num_local_steps: 25
num_mini_batch: auto
num_processes: 5
num_processes_on_first_gpu: 1
num_processes_per_gpu: 6
num_sem_categories: 16
num_train_episodes: 10000
num_training_frames: 10000000
ppo_epoch: 4
print_images: 0
reward_coeff: 0.1
save_interval: 1
save_periodic: 500000
seed: 1
sem_gpu_id: -1
sem_pred_prob_thr: 0.9
sim_gpu_id: 0
split: train
success_dist: 1.0
task_config: tasks/objectnav_hm3d.yaml
tau: 0.95
total_num_scenes: auto
train_se_f: 0
turn_angle: 30
use_gae: false
use_gtsem: 0
use_recurrent_global: 0
value_loss_coef: 0.5
version: v1.1
vision_range: 100
visualize: 0
