defaults:
  - base_config
  - environment: hm3d
  - agent: base_agent
  - objectnav
  - _self_

general:
  seed: 1
  auto_gpu_config: 1
  total_num_scenes: "auto"
  num_processes: 5
  num_processes_per_gpu: 6
  num_processes_on_first_gpu: 1
  no_cuda: False
  simulation_gpu_id: 0
  segmentation_gpu_id: 0

agent:
  agent_gpu_id: 0
  eval: 1
  num_training_frames: 10_000_000
  num_eval_episodes: 400
  num_train_episodes: 10_000
  log_interval: 10
  model_save_interval: 1
  model_save_frequency: 500_000
  agent_type: "sem_exp"
  learning_rate: 2.5e-5
  global_hidden_states: 256
  epsilon: 1e-5
  alpha: 0.99
  gamma: 0.99
  use_gae: False
  tau: 0.95
  entropy_coef: 0.001
  value_loss_coef: 0.5
  max_grad_norm: 0.5
  num_global_steps: 20
  num_ppo_epochs: 4
  num_mini_batches: 32
  clip_threshold: 0.2
  use_recurrent_global: False
  num_local_steps: 25
  intrinsic_reward_coef: 0.05
  num_sem_categories: 16
sem_map:
  vision_range: 100
  map_resolution: 5
  du_scale: 1
  map_size_cm: 4800
  cat_pred_threshold: 5.0
  map_pred_threshold: 1.0
  exp_pred_threshold: 1.0
  collision_threshold: 0.10
  use_gt_sem: False

path:
  model: ""
  task_config: "env/habitat/config/tasks"
  maskrcnn_config: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
  maskrcnn_weights: "detectron2://COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x/137849600/model_final_f10217.pkl"
visualize:
  visualize: False
  print_images: False

data:
  version: "v1.0"
